# Generated by Django 4.2.3 on 2023-07-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_rename_item_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
    ]
